site_name: Learn To HomeLab
theme: 
  name: material
  favicon: /images/logo/favicon.png
  logo: /images/logo/favicon.png
  font:
    text: Helvetica

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode 
      primary: custom
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: custom
      accent: lime

  plugins:
  
  - social
  - search
  - material
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: hhttps://github.com/LearnToHomeLab
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UChC4ztzEchbm0nxIhw5zyog
  analytics:
    provider: google
    property: G-8W8J33P5JD
  consent:
    title: Cookie consent
    description: > # (1)
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
extra_css:
    - custom.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Home: index.md #anything at this level will show as a tab at the top of the page
  - Homelab Series:
      - EP 0 - Start Guide: homelabseries/EP0_startguide.md
      - EP 1 - Note Keeping: homelabseries/EP1_notekeeping.md
      - EP 2 - Switch Install: homelabseries/EP2_switch.md
      - EP 3 - Firewall Install: homelabseries/EP3_firewall.md
      - EP 4 - Proxmox Install: homelabseries/EP4_proxmox.md
      - EP 5 - Setting up your first VM: homelabseries/EP5_firstvmubuntu.md
      - EP 6 - Setting up your first Video Game Server (Minecraft Example): homelabseries/EP6_firstvideogameserver.md
      - EP 7 - Set up Pihole with Proxmox: homelabseries/EP7_setuppihole.md  
      - EP 8 - NextCloud with Proxmox: homelabseries/EP8_nextcloud.md
  - Hardware Reviews:
      - EP 0 - Unifi Flex Mini 2.5G: hardwarereview/ep0_unififlex2gig.md
  - Software Tutorials:
      - EP 0 - Unbound DNS and Ad Blocker in OPNsense:  SoftwareVideoNotes/EP0_UnboundDNS.md

copyright: |
  &copy; 2024 <a href="https://www.youtube.com/channel/UChC4ztzEchbm0nxIhw5zyog"  target="_blank" rel="noopener">Learn To Homelab</a>